# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManagementUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 606)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(600, 310, 171, 81))
        self.pushButton_4.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(830, 130, 111, 51))
        self.pushButton_5.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 70, 191, 31))
        self.label.setStyleSheet("font: 14pt \"Algerian\";")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 310, 181, 81))
        self.pushButton_2.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 120, 171, 71))
        self.pushButton.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(350, 60, 251, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 310, 171, 81))
        self.pushButton_3.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 130, 171, 31))
        self.label_2.setStyleSheet("font: 14pt \"Algerian\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(350, 130, 251, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 210, 241, 21))
        self.label_3.setStyleSheet("font: 14pt \"Algerian\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 200, 251, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(600, 410, 171, 81))
        self.pushButton_6.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(390, 410, 171, 81))
        self.pushButton_7.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 410, 181, 81))
        self.pushButton_8.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton_8.setObjectName("pushButton_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_5.clicked.connect(self.lineEdit.clear) # type: ignore
        self.pushButton_5.clicked.connect(self.lineEdit_2.clear) # type: ignore
        self.pushButton_5.clicked.connect(self.lineEdit_3.clear) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.slot1) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.slot2) # type: ignore
        self.pushButton_4.clicked.connect(MainWindow.slot3) # type: ignore
        self.pushButton_8.clicked.connect(MainWindow.slot4) # type: ignore
        self.pushButton_7.clicked.connect(MainWindow.slot5) # type: ignore
        self.pushButton_6.clicked.connect(MainWindow.slot6) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "监管机构主界面（颁发许可证）"))
        self.pushButton_4.setText(_translate("MainWindow", "查看疫苗生产记录"))
        self.pushButton_5.setText(_translate("MainWindow", "刷新"))
        self.label.setText(_translate("MainWindow", "请输入管理机构ID"))
        self.pushButton_2.setText(_translate("MainWindow", "查看生产许可证"))
        self.pushButton.setText(_translate("MainWindow", "颁发许可证"))
        self.pushButton_3.setText(_translate("MainWindow", "查询接种信息"))
        self.label_2.setText(_translate("MainWindow", "请输入生产商ID"))
        self.label_3.setText(_translate("MainWindow", "请输入生产许可证期限"))
        self.pushButton_6.setText(_translate("MainWindow", "查询仓库存储关系"))
        self.pushButton_7.setText(_translate("MainWindow", "查看疫苗入库记录"))
        self.pushButton_8.setText(_translate("MainWindow", "查看疫苗交易订单"))
