# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HospVacAppointmentUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 554)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 40, 141, 21))
        self.label.setStyleSheet("font: 14pt \"Algerian\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 30, 251, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(520, 330, 141, 71))
        self.pushButton_5.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 330, 181, 71))
        self.pushButton.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 110, 171, 31))
        self.label_2.setStyleSheet("font: 14pt \"Algerian\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 110, 251, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 180, 171, 31))
        self.label_3.setStyleSheet("font: 14pt \"Algerian\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(380, 180, 251, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 270, 181, 31))
        self.label_4.setStyleSheet("font: 14pt \"Algerian\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 260, 91, 41))
        self.lineEdit_4.setStyleSheet("font: 14pt \"Algerian\";")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(430, 260, 91, 41))
        self.lineEdit_5.setStyleSheet("font: 14pt \"Algerian\";")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(540, 260, 91, 41))
        self.lineEdit_6.setStyleSheet("font: 14pt \"Algerian\";")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(650, 260, 91, 41))
        self.lineEdit_7.setStyleSheet("font: 14pt \"Algerian\";")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(760, 260, 91, 41))
        self.lineEdit_8.setStyleSheet("font: 14pt \"Algerian\";")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 420, 171, 61))
        self.pushButton_2.setStyleSheet("font: 12pt \"Algerian\";")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 944, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_5.clicked.connect(self.lineEdit_4.clear) # type: ignore
        self.pushButton_5.clicked.connect(self.lineEdit_5.clear) # type: ignore
        self.pushButton_5.clicked.connect(self.lineEdit_6.clear) # type: ignore
        self.pushButton_5.clicked.connect(self.lineEdit_7.clear) # type: ignore
        self.pushButton_5.clicked.connect(self.lineEdit_8.clear) # type: ignore
        self.pushButton_5.clicked.connect(self.lineEdit_3.clear) # type: ignore
        self.pushButton_5.clicked.connect(self.lineEdit_2.clear) # type: ignore
        self.pushButton_5.clicked.connect(self.lineEdit.clear) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.slot1) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "处理接种预约"))
        self.label.setText(_translate("MainWindow", "请输入本院ID"))
        self.pushButton_5.setText(_translate("MainWindow", "刷新"))
        self.pushButton.setText(_translate("MainWindow", "更新预约记录"))
        self.label_2.setText(_translate("MainWindow", "请输入预约编号"))
        self.label_3.setText(_translate("MainWindow", "请输入接种情况"))
        self.label_4.setText(_translate("MainWindow", "请输入具体时间"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "年"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "月"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "日"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "时"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "分"))
        self.pushButton_2.setText(_translate("MainWindow", "返回"))
